name: stoorps-dev
id: stoorps-dev
vibversion: 1.0.0
stages:
- id: build
  base: fedora:latest 
  singlelayer: false
  labels:
    maintainer: stoorps

  modules:
  - name: modules
    type: includes
    includes:
      - modules/00-rustup.yml
      - modules/01-vscode.yml
      - modules/02-dnf-install.yml
      - modules/03-git-config.yml
      - modules/04-zed.yml
      - modules/80-set-image-abroot-config.yml


  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources

