name: stoorps-dev
id: stoorps-dev
stages:
- id: build
  base: fedora:latest 
  singlelayer: false
  labels:
    maintainer: stoorps

  modules:
  - name: init-setup
    type: shell
    commands:
   # Rustup
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y 
    - . "$HOME/.cargo/env" 
  # Vs Code
    - sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    - echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null
    - dnf check-update
    - sudo dnf install code git gh nano -y

  # Git config
    - git config --global user.email stoorps@proton.me 
    - git config --global user.name stoorps 
    - git config --global gpg.format ssh 
    - git config --global user.signingkey /var/home/stoorps/.ssh/github.pub
    - git config --global commit.gpgsign true
    - git config --global tag.gpgSign true

  # Zed setup
    - curl -f https://zed.dev/install.sh | sh

  - name: set-image-name-abroot
    type: includes
    includes:
      - modules/80-set-image-abroot-config.yml


  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources

